CREATE TABLE IF NOT EXISTS {TRIP_UPDATE_TABLE} (
    {ID_KEY} INT AUTO_INCREMENT PRIMARY KEY,
    {FEED_TIMESTAMP_KEY} TIMESTAMP,
    {TRIP_ID_KEY} VARCHAR(50),
    {TRIP_SCHEDULE_RELATIONSHIP_KEY} INT,
    {TRIP_ROUTE_ID_KEY} VARCHAR(20),
    {TRIP_DIRECTION_ID_KEY} INT,
    {STOP_SEQUENCE_KEY} INT,
    {STOP_ID_KEY} VARCHAR(50),
    {SCHEDULE_RELATIONSHIP_KEY} INT,
    {ARRIVAL_DELAY_KEY} INT,
    {ARRIVAL_TIME_KEY} TIMESTAMP,
    {ARRIVAL_UNCERTAINTY_KEY} INT,
    {DEPARTURE_DELAY_KEY} INT,
    {DEPARTURE_TIME_KEY} TIMESTAMP,
    {DEPARTURE_UNCERTAINTY_KEY} INT,
    {TRIP_START_TIMESTAMP_KEY} TIMESTAMP
);
