INSERT INTO {TRIP_UPDATE_TABLE} (
    {FEED_TIMESTAMP_KEY},
    {TRIP_ID_KEY},
    {TRIP_SCHEDULE_RELATIONSHIP_KEY},
    {TRIP_ROUTE_ID_KEY},
    {TRIP_DIRECTION_ID_KEY},
    {STOP_SEQUENCE_KEY},
    {STOP_ID_KEY},
    {SCHEDULE_RELATIONSHIP_KEY},
    {ARRIVAL_DELAY_KEY},
    {ARRIVAL_TIME_KEY},
    {ARRIVAL_UNCERTAINTY_KEY},
    {DEPARTURE_DELAY_KEY},
    {DEPARTURE_TIME_KEY},
    {DEPARTURE_UNCERTAINTY_KEY},
    {TRIP_START_TIMESTAMP_KEY}
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
