CREATE TABLE IF NOT EXISTS {VEHICLE_UPDATE_TABLE} (
    {ID_KEY} INT AUTO_INCREMENT PRIMARY KEY,
    {VehicleTableIngestionFields.feed_timestamp} TIMESTAMP,
    {VehicleTableIngestionFields.entity_id} INT,
    {VehicleTableIngestionFields.trip_id} VARCHAR(50),
    {VehicleTableIngestionFields.trip_schedule_relationship} INT,
    {VehicleTableIngestionFields.trip_route_id} VARCHAR(20),
    {VehicleTableIngestionFields.trip_direction_id} INT,
    {VehicleTableIngestionFields.position_latitude} DOUBLE,
    {VehicleTableIngestionFields.position_longitude} DOUBLE,
    {VehicleTableIngestionFields.position_bearing} DOUBLE,
    {VehicleTableIngestionFields.position_odometer} DOUBLE,
    {VehicleTableIngestionFields.position_speed} DOUBLE,
    {VehicleTableIngestionFields.current_stop_sequence} INT,
    {VehicleTableIngestionFields.current_status} INT,
    {VehicleTableIngestionFields.timestamp} TIMESTAMP,
    {VehicleTableIngestionFields.congestion_level} INT,
    {VehicleTableIngestionFields.stop_id} VARCHAR(50),
    {VehicleTableIngestionFields.vehicle_id} VARCHAR(50),
    {VehicleTableIngestionFields.vehicle_label} VARCHAR(50),
    {VehicleTableIngestionFields.trip_start_timestamp} TIMESTAMP,
    {READ_TIMESTAMP_KEY} TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
