CREATE TABLE IF NOT EXISTS {VEHICLE_UPDATE_TABLE} (
    {ID_KEY} INT AUTO_INCREMENT PRIMARY KEY,
    {VehicleTableIngestionFields.FEED_TIMESTAMP} TIMESTAMP,
    {VehicleTableIngestionFields.ENTITY_ID} INT,
    {VehicleTableIngestionFields.TRIP_ID} VARCHAR(50),
    {VehicleTableIngestionFields.TRIP_SCHEDULE_RELATIONSHIP} INT,
    {VehicleTableIngestionFields.TRIP_ROUTE_ID} VARCHAR(20),
    {VehicleTableIngestionFields.TRIP_DIRECTION_ID} INT,
    {VehicleTableIngestionFields.POSITION_LATITUDE} DOUBLE,
    {VehicleTableIngestionFields.POSITION_LONGITUDE} DOUBLE,
    {VehicleTableIngestionFields.POSITION_BEARING} DOUBLE,
    {VehicleTableIngestionFields.POSITION_ODOMETER} DOUBLE,
    {VehicleTableIngestionFields.POSITION_SPEED} DOUBLE,
    {VehicleTableIngestionFields.CURRENT_STOP_SEQUENCE} INT,
    {VehicleTableIngestionFields.CURRENT_STATUS} INT,
    {VehicleTableIngestionFields.TIMESTAMP} TIMESTAMP,
    {VehicleTableIngestionFields.CONGESTION_LEVEL} INT,
    {VehicleTableIngestionFields.STOP_ID} VARCHAR(50),
    {VehicleTableIngestionFields.VEHICLE_ID} VARCHAR(50),
    {VehicleTableIngestionFields.VEHICLE_LABEL} VARCHAR(50),
    {VehicleTableIngestionFields.TRIP_START_TIMESTAMP} TIMESTAMP,
    {READ_TIMESTAMP_KEY} TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
