"""
SQL queries for creating table and inserting data into the database.

TODO:
- Move these queries to actual sql files and load them as needed.
"""

from . import constants as cons

VEHICLE_UPDATE_TABLE = cons.VEHICLE_UPDATE_TABLE
TRIP_UPDATE_TABLE = cons.TRIP_UPDATE_TABLE

VEHICLE_UPDATES_CREATE_TABLE_QUERY = f"""
CREATE TABLE IF NOT EXISTS {cons.VEHICLE_UPDATE_TABLE} (
    {cons.ID_KEY} INT AUTO_INCREMENT PRIMARY KEY,
    {cons.FEED_TIMESTAMP_KEY} TIMESTAMP,
    {cons.ENTITY_ID_KEY} INT,
    {cons.TRIP_ID_KEY} VARCHAR(50),
    {cons.TRIP_SCHEDULE_RELATIONSHIP_KEY} INT,
    {cons.TRIP_ROUTE_ID_KEY} VARCHAR(20),
    {cons.TRIP_DIRECTION_ID_KEY} INT,
    {cons.POSITION_LATITUDE_KEY} DOUBLE,
    {cons.POSITION_LONGITUDE_KEY} DOUBLE,
    {cons.POSITION_BEARING_KEY} DOUBLE,
    {cons.POSITION_ODOMETER_KEY} DOUBLE,
    {cons.POSITION_SPEED_KEY} DOUBLE,
    {cons.CURRENT_STOP_SEQUENCE_KEY} INT,
    {cons.CURRENT_STATUS_KEY} INT,
    {cons.TIMESTAMP_KEY} TIMESTAMP,
    {cons.CONGESTION_LEVEL_KEY} INT,
    {cons.STOP_ID_KEY} VARCHAR(50),
    {cons.VEHICLE_ID_KEY} VARCHAR(50),
    {cons.VEHICLE_LABEL_KEY} VARCHAR(50),
    {cons.TRIP_START_TIMESTAMP_KEY} TIMESTAMP,
    {cons.READ_TIMESTAMP_KEY} TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

VEHICLE_UPDATES_INSERT_QUERY = f"""
INSERT INTO {cons.VEHICLE_UPDATE_TABLE} (
    {cons.FEED_TIMESTAMP_KEY}, {cons.ENTITY_ID_KEY}, {cons.TRIP_ID_KEY}, {cons.TRIP_SCHEDULE_RELATIONSHIP_KEY},
    {cons.TRIP_ROUTE_ID_KEY}, {cons.TRIP_DIRECTION_ID_KEY}, {cons.POSITION_LATITUDE_KEY}, {cons.POSITION_LONGITUDE_KEY},
    {cons.POSITION_BEARING_KEY}, {cons.POSITION_ODOMETER_KEY}, {cons.POSITION_SPEED_KEY}, {cons.CURRENT_STOP_SEQUENCE_KEY},
    {cons.CURRENT_STATUS_KEY}, {cons.TIMESTAMP_KEY}, {cons.CONGESTION_LEVEL_KEY}, {cons.STOP_ID_KEY}, {cons.VEHICLE_ID_KEY},
    {cons.VEHICLE_LABEL_KEY}, {cons.TRIP_START_TIMESTAMP_KEY}
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

TRIP_UPDATES_CREATE_TABLE_QUERY = f"""
CREATE TABLE IF NOT EXISTS {cons.TRIP_UPDATE_TABLE} (
    {cons.ID_KEY} INT AUTO_INCREMENT PRIMARY KEY,
    {cons.FEED_TIMESTAMP_KEY} TIMESTAMP,
    {cons.TRIP_ID_KEY} VARCHAR(50),
    {cons.TRIP_SCHEDULE_RELATIONSHIP_KEY} INT,
    {cons.TRIP_ROUTE_ID_KEY} VARCHAR(20),
    {cons.TRIP_DIRECTION_ID_KEY} INT,
    {cons.STOP_SEQUENCE_KEY} INT,
    {cons.STOP_ID_KEY} VARCHAR(50),
    {cons.SCHEDULE_RELATIONSHIP_KEY} INT,
    {cons.ARRIVAL_DELAY_KEY} INT,
    {cons.ARRIVAL_TIME_KEY} TIMESTAMP,
    {cons.ARRIVAL_UNCERTAINTY_KEY} INT,
    {cons.DEPARTURE_DELAY_KEY} INT,
    {cons.DEPARTURE_TIME_KEY} TIMESTAMP,
    {cons.DEPARTURE_UNCERTAINTY_KEY} INT,
    {cons.TRIP_START_TIMESTAMP_KEY} TIMESTAMP
);
"""

TRIP_UPDATES_INSERT_QUERY = f"""
INSERT INTO {cons.TRIP_UPDATE_TABLE} (
    {cons.FEED_TIMESTAMP_KEY},
    {cons.TRIP_ID_KEY},
    {cons.TRIP_SCHEDULE_RELATIONSHIP_KEY},
    {cons.TRIP_ROUTE_ID_KEY},
    {cons.TRIP_DIRECTION_ID_KEY},
    {cons.STOP_SEQUENCE_KEY},
    {cons.STOP_ID_KEY},
    {cons.SCHEDULE_RELATIONSHIP_KEY},
    {cons.ARRIVAL_DELAY_KEY},
    {cons.ARRIVAL_TIME_KEY},
    {cons.ARRIVAL_UNCERTAINTY_KEY},
    {cons.DEPARTURE_DELAY_KEY},
    {cons.DEPARTURE_TIME_KEY},
    {cons.DEPARTURE_UNCERTAINTY_KEY},
    {cons.TRIP_START_TIMESTAMP_KEY}
) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
"""
